version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: taskmgmt_db
    restart: always
    environment:
      POSTGRES_DB: task_mgmt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-network

  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: abhise203/taskflow-app:backend  
    container_name: taskmgmt_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=task_mgmt_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - taskflow-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: abhise203/taskflow-app:frontend  
    container_name: taskmgmt_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - taskflow-network

volumes:
  postgres_data:

networks:
  taskflow-network:
    driver: bridge  